[package]
name = "snappy-rs"
version = "0.1.0"
authors = ["1521350289@qq.com <1521350289@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc="0.2"
